"""empty message

Revision ID: 11a89972c65e
Revises: 987853138256
Create Date: 2023-08-18 15:26:07.111028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11a89972c65e'
down_revision = '987853138256'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('employee_request_employee_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'employee', ['employee_id'], ['id'])
        batch_op.drop_column('employee')

    with op.batch_alter_table('fund_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zone_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('domaine_activite_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('centre_de_cout_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fund_request_centre_de_cout_fkey', type_='foreignkey')
        batch_op.drop_constraint('fund_request_domaine_activite_fkey', type_='foreignkey')
        batch_op.drop_constraint('fund_request_zone_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'activity_domain', ['domaine_activite_id'], ['id'])
        batch_op.create_foreign_key(None, 'cost_center', ['centre_de_cout_id'], ['id'])
        batch_op.create_foreign_key(None, 'zone', ['zone_id'], ['id'])
        batch_op.drop_column('centre_de_cout')
        batch_op.drop_column('zone')
        batch_op.drop_column('domaine_activite')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fund_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('domaine_activite', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('zone', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('centre_de_cout', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fund_request_zone_fkey', 'zone', ['zone'], ['id'])
        batch_op.create_foreign_key('fund_request_domaine_activite_fkey', 'activity_domain', ['domaine_activite'], ['id'])
        batch_op.create_foreign_key('fund_request_centre_de_cout_fkey', 'cost_center', ['centre_de_cout'], ['id'])
        batch_op.drop_column('centre_de_cout_id')
        batch_op.drop_column('domaine_activite_id')
        batch_op.drop_column('zone_id')

    with op.batch_alter_table('employee_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('employee_request_employee_fkey', 'employee', ['employee'], ['id'])
        batch_op.drop_column('employee_id')

    # ### end Alembic commands ###
