"""empty message

Revision ID: 1393d6be701b
Revises: 61430f1196bb
Create Date: 2023-08-21 10:52:08.362636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1393d6be701b'
down_revision = '61430f1196bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_domain', schema=None) as batch_op:
        batch_op.alter_column('plant',
               existing_type=sa.VARCHAR(length=4),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_domain', schema=None) as batch_op:
        batch_op.alter_column('plant',
               existing_type=sa.VARCHAR(length=4),
               nullable=True)

    # ### end Alembic commands ###
