"""empty message

Revision ID: 179f674d84c1
Revises: c0cff677d33b
Create Date: 2023-09-26 16:38:40.851909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '179f674d84c1'
down_revision = 'c0cff677d33b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature_filename', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('initial_filename', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('initial_filename')
        batch_op.drop_column('signature_filename')

    # ### end Alembic commands ###
