"""empty message

Revision ID: 1af1a8a9c7ac
Revises: 14ca8d76aed6
Create Date: 2023-09-28 12:38:34.145495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1af1a8a9c7ac'
down_revision = '14ca8d76aed6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fund_request', schema=None) as batch_op:
        batch_op.drop_column('odm_filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fund_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('odm_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
