"""empty message

Revision ID: 37e72556a491
Revises: 11a89972c65e
Create Date: 2023-08-21 10:35:10.337719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37e72556a491'
down_revision = '11a89972c65e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fund_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('odm_filename', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=False))

    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('montant_perdiem', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('montant_logement', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.drop_column('montant_logement')
        batch_op.drop_column('montant_perdiem')

    with op.batch_alter_table('fund_request', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('odm_filename')

    # ### end Alembic commands ###
