"""empty message

Revision ID: 61430f1196bb
Revises: 63d1c075205c
Create Date: 2023-08-21 10:50:33.369944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61430f1196bb'
down_revision = '63d1c075205c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_domain', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plant', sa.String(length=4), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_domain', schema=None) as batch_op:
        batch_op.drop_column('plant')

    # ### end Alembic commands ###
