"""empty message

Revision ID: 86e9fe164313
Revises: 953a205edd6d
Create Date: 2023-08-22 13:57:18.197910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86e9fe164313'
down_revision = '953a205edd6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_approval_datetime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_request_id', sa.Integer(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('approved_or_reject', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['fund_request_id'], ['fund_request.id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['user_level.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request_approval_datetime')
    # ### end Alembic commands ###
