"""empty message

Revision ID: 8843e3699543
Revises: e8d5971b2a3c
Create Date: 2023-08-21 11:27:43.941680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8843e3699543'
down_revision = 'e8d5971b2a3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade_zone', schema=None) as batch_op:
        batch_op.add_column(sa.Column('montant_peage', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade_zone', schema=None) as batch_op:
        batch_op.drop_column('montant_peage')

    # ### end Alembic commands ###
