"""empty message

Revision ID: 9004f4c9b764
Revises: e3c11871074f
Create Date: 2023-08-22 10:19:44.272279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9004f4c9b764'
down_revision = 'e3c11871074f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_request', schema=None) as batch_op:
        batch_op.alter_column('montant_perdiem',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('montant_logement',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('montant_peage',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('fund_request', schema=None) as batch_op:
        batch_op.alter_column('approval_level',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fund_request', schema=None) as batch_op:
        batch_op.alter_column('approval_level',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('employee_request', schema=None) as batch_op:
        batch_op.alter_column('montant_peage',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('montant_logement',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('montant_perdiem',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
