"""empty message

Revision ID: 953a205edd6d
Revises: e24c79814af4
Create Date: 2023-08-22 13:55:04.878974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '953a205edd6d'
down_revision = 'e24c79814af4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fund_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fund_request', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
