"""empty message

Revision ID: 987853138256
Revises: b1bf559fec76
Create Date: 2023-08-18 15:23:13.754642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '987853138256'
down_revision = 'b1bf559fec76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('employee_grade_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'grade', ['grade_id'], ['id'])
        batch_op.drop_column('grade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('employee_grade_fkey', 'grade', ['grade'], ['id'])
        batch_op.drop_column('grade_id')

    # ### end Alembic commands ###
