"""empty message

Revision ID: aeb5016ea1f6
Revises: 1a66bb76970d
Create Date: 2023-08-21 13:18:44.779074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeb5016ea1f6'
down_revision = '1a66bb76970d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fund_request_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('employee_request_fund_request_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'fund_request', ['fund_request_id'], ['id'])
        batch_op.drop_column('fund_request')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fund_request', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('employee_request_fund_request_fkey', 'fund_request', ['fund_request'], ['id'])
        batch_op.drop_column('fund_request_id')

    # ### end Alembic commands ###
