"""empty message

Revision ID: b74f1374f69a
Revises: 8146fefd1f4a
Create Date: 2023-08-21 18:14:16.279059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b74f1374f69a'
down_revision = '8146fefd1f4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=50), nullable=False),
    sa.Column('level', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('firstname_lastname', sa.String(length=150), nullable=False),
    sa.Column('user_level_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_level_id'], ['user_level.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('user_level')
    # ### end Alembic commands ###
