"""empty message

Revision ID: d19cded98df9
Revises: 164feb28ecc9
Create Date: 2023-08-24 13:46:18.684441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd19cded98df9'
down_revision = '164feb28ecc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fund_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nom_prenoms_chauffeur', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fund_request', schema=None) as batch_op:
        batch_op.drop_column('nom_prenoms_chauffeur')

    # ### end Alembic commands ###
