"""empty message

Revision ID: da83ec9f51d2
Revises: aeb5016ea1f6
Create Date: 2023-08-21 15:06:29.154303

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da83ec9f51d2'
down_revision = 'aeb5016ea1f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('montant_perdiem', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('montant_logement', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('montant_peage', sa.Integer(), nullable=True))

    with op.batch_alter_table('fund_request', schema=None) as batch_op:
        batch_op.alter_column('date_debut',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('date_fin',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fund_request', schema=None) as batch_op:
        batch_op.alter_column('date_fin',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('date_debut',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('employee_request', schema=None) as batch_op:
        batch_op.drop_column('montant_peage')
        batch_op.drop_column('montant_logement')
        batch_op.drop_column('montant_perdiem')

    # ### end Alembic commands ###
