"""empty message

Revision ID: e24c79814af4
Revises: 91f94b2b062b
Create Date: 2023-08-22 10:40:02.933348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e24c79814af4'
down_revision = '91f94b2b062b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fund_request', schema=None) as batch_op:
        batch_op.alter_column('reject_reason',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fund_request', schema=None) as batch_op:
        batch_op.alter_column('reject_reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
